# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: my-node-service
  namespace: monitoring
spec:
  type: LoadBalancer       # ✅ Change this
  selector:
    app: my-node-app
  ports:
    - port: 3000
      targetPort: 3000

